services:
  # model:
  #   build: .
  #   image: model:latest
  #   container_name: modelinstance
  #   volumes:
  #   - .:/app
  #   ports:
  #   - '8888:8888'
  fastapi:
    build: 
      context: .
      dockerfile: api.Dockerfile
    image: fast-api:latest
    container_name: fastapiinstance
    ports:
    - '8000:8000'